# Generated by Django 2.1.3 on 2020-01-17 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_remove_feorder_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='feorder',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feorder',
            name='goods',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feorder',
            name='oriprice',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feorder',
            name='pay_type',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='feorder',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feorder',
            name='status',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
