# Generated by Django 2.1.3 on 2019-12-18 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('good', '0008_auto_20191216_1335'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('keyword', models.CharField(blank=True, max_length=128, null=True)),
                ('desc', models.CharField(blank=True, max_length=512, null=True)),
                ('photos', models.CharField(blank=True, max_length=2048, null=True)),
                ('banner_pc', models.CharField(blank=True, max_length=2048, null=True)),
                ('banner_mobile', models.CharField(blank=True, max_length=2048, null=True)),
                ('bgcolor', models.CharField(blank=True, max_length=64, null=True)),
                ('start_at', models.DateTimeField(blank=True, null=True)),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.IntegerField(blank=True, default=0, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SessionGoodsRelate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('goods', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='as_good_session', to='good.Goods')),
                ('session', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='as_session_good', to='session.Session')),
            ],
        ),
    ]
