# Generated by Django 2.1.3 on 2019-12-21 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessiongoodsrelate',
            name='status',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='session',
            name='status',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
