# Generated by Django 2.1.3 on 2019-12-22 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0002_auto_20191221_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessiongoodsrelate',
            name='goods',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='as_good_session', to='good.Goods'),
        ),
        migrations.AlterField(
            model_name='sessiongoodsrelate',
            name='session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='as_session_good', to='session.Session'),
        ),
    ]
