# Generated by Django 2.1.3 on 2019-12-22 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('good', '0008_auto_20191216_1335'),
        ('session', '0003_auto_20191222_0013'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sessiongoodsrelate',
            unique_together={('goods', 'session')},
        ),
    ]
