# Generated by Django 2.1.3 on 2020-01-16 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fecart',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='feuser.Feuser'),
        ),
    ]
