# Generated by Django 2.1.3 on 2020-01-16 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_auto_20200116_0840'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fecart',
            name='address',
        ),
        migrations.RemoveField(
            model_name='fecart',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='fecart',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='fecart',
            name='user',
        ),
    ]
