# Generated by Django 2.1.3 on 2020-01-16 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feuser', '0004_auto_20200115_1116'),
        ('cart', '0003_auto_20200116_0910'),
    ]

    operations = [
        migrations.AddField(
            model_name='fecart',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='feuser.FeAddress'),
        ),
        migrations.AddField(
            model_name='fecart',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='fecart',
            name='goods',
            field=models.TextField(default='[]'),
        ),
        migrations.AddField(
            model_name='fecart',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fecart',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='fecart',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='feuser.Feuser'),
        ),
    ]
