# Generated by Django 2.1.3 on 2020-01-16 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_auto_20200116_0914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fecart',
            name='address',
        ),
    ]
