# Generated by Django 2.1.3 on 2020-01-15 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feuser', '0002_auto_20200114_0725'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('street', models.CharField(max_length=512)),
                ('street_ext', models.CharField(max_length=512)),
                ('city', models.CharField(max_length=64)),
                ('district', models.CharField(max_length=64)),
                ('country', models.CharField(max_length=64)),
                ('code', models.CharField(max_length=10)),
                ('is_default', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='feuser.Feuser')),
            ],
        ),
    ]
