# Generated by Django 2.1.3 on 2020-01-15 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feuser', '0003_feaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feaddress',
            name='city',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='feaddress',
            name='code',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='feaddress',
            name='country',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='feaddress',
            name='district',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='feaddress',
            name='street_ext',
            field=models.CharField(max_length=512, null=True),
        ),
    ]
