# Generated by Django 2.1.3 on 2019-11-19 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('category_id', models.IntegerField(blank=True, null=True)),
                ('promotion', models.CharField(blank=True, max_length=256, null=True)),
                ('keyword', models.CharField(blank=True, max_length=256, null=True)),
                ('unit', models.CharField(blank=True, max_length=45, null=True)),
                ('tags', models.CharField(blank=True, max_length=256, null=True)),
                ('brand_id', models.IntegerField(blank=True, null=True)),
                ('supplier_id', models.IntegerField(blank=True, null=True)),
                ('base_sale', models.IntegerField(blank=True, null=True)),
                ('base_click', models.IntegerField(blank=True, null=True)),
                ('base_share', models.IntegerField(blank=True, null=True)),
                ('product_code', models.CharField(blank=True, max_length=128, null=True)),
                ('starttime', models.DateField(blank=True, null=True)),
                ('validity_period', models.IntegerField(blank=True, null=True)),
                ('inventory', models.IntegerField(blank=True, null=True)),
                ('inventory_warn', models.IntegerField(blank=True, null=True)),
                ('place', models.CharField(blank=True, max_length=256, null=True)),
                ('sku_ids', models.CharField(blank=True, max_length=512, null=True)),
                ('photo', models.CharField(blank=True, max_length=256, null=True)),
                ('type_id', models.IntegerField(blank=True, null=True)),
                ('media', models.CharField(blank=True, max_length=256, null=True)),
                ('detail', models.TextField(blank=True, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GoodsAlbum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('sort', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GoodsBrand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64, null=True)),
                ('desc', models.CharField(blank=True, max_length=256, null=True)),
                ('is_recommend', models.SmallIntegerField(blank=True, null=True)),
                ('photo', models.CharField(blank=True, max_length=256, null=True)),
                ('brand_photo', models.CharField(blank=True, max_length=256, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GoodsCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('name_simple', models.CharField(blank=True, max_length=128, null=True)),
                ('goods_type', models.IntegerField(blank=True, null=True)),
                ('is_show', models.SmallIntegerField(blank=True, null=True)),
                ('sort', models.IntegerField(blank=True, null=True)),
                ('photo', models.CharField(blank=True, max_length=256, null=True)),
                ('keyword', models.CharField(blank=True, max_length=45, null=True)),
                ('desc', models.CharField(blank=True, max_length=256, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GoodsPic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(blank=True, max_length=512, null=True)),
                ('size', models.CharField(blank=True, max_length=45, null=True)),
                ('width', models.CharField(blank=True, max_length=45, null=True)),
                ('height', models.CharField(blank=True, max_length=45, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('album', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='as_album', to='good.GoodsAlbum')),
            ],
        ),
        migrations.CreateModel(
            name='GoodsSku',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_id', models.IntegerField()),
                ('name', models.CharField(max_length=128)),
                ('attr_values_items', models.CharField(blank=True, max_length=256, null=True)),
                ('market_price', models.DecimalField(decimal_places=0, max_digits=10)),
                ('price', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('promote_price', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('cost_price', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('stock', models.IntegerField()),
                ('photo', models.CharField(blank=True, max_length=256, null=True)),
                ('detail', models.TextField(blank=True, null=True)),
                ('code', models.CharField(blank=True, max_length=256, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GoodsSpec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('sort', models.IntegerField(blank=True, null=True)),
                ('is_used', models.SmallIntegerField(blank=True, null=True)),
                ('values', models.CharField(max_length=128)),
                ('desc', models.CharField(blank=True, max_length=256, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GoodsSupplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('contact', models.CharField(blank=True, max_length=128, null=True)),
                ('phone', models.CharField(blank=True, max_length=45, null=True)),
                ('address', models.CharField(blank=True, max_length=256, null=True)),
                ('desc', models.CharField(blank=True, max_length=512, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GoodsTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=45, null=True)),
                ('sort', models.IntegerField(blank=True, null=True)),
                ('photo', models.CharField(blank=True, max_length=256, null=True)),
                ('desc', models.CharField(blank=True, max_length=256, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GoodsType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=45, null=True)),
                ('sort', models.IntegerField(blank=True, null=True)),
                ('is_used', models.SmallIntegerField(blank=True, null=True)),
                ('attrs', models.CharField(blank=True, max_length=256, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='goods',
            name='picture',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='as_picture', to='good.GoodsPic'),
        ),
    ]
