# Generated by Django 2.1.7 on 2019-11-22 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('good', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='status',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
