# Generated by Django 2.1.7 on 2019-11-22 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('good', '0002_auto_20191122_0242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='photo',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
    ]
