# Generated by Django 2.1.3 on 2019-12-14 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('good', '0004_auto_20191128_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodssku',
            name='attr_values_items',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='goodssku',
            name='code',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='goodssku',
            name='name',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='goodssku',
            name='photo',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='goodssku',
            name='stock',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
