# Generated by Django 2.1.3 on 2019-12-14 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('good', '0005_auto_20191214_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodssku',
            name='goods',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='as_good', to='good.Goods', unique=True),
        ),
    ]
