# Generated by Django 2.1.3 on 2019-12-14 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('good', '0006_auto_20191214_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodssku',
            name='goods',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='as_good', to='good.Goods'),
        ),
    ]
