# Generated by Django 2.1.3 on 2020-01-10 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('good', '0008_auto_20191216_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodscategory',
            name='level',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
