# Generated by Django 2.1.3 on 2020-01-10 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('good', '0009_goodscategory_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodscategory',
            name='oriphoto',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
