# Generated by Django 2.1.3 on 2020-01-10 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('good', '0010_goodscategory_oriphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodscategory',
            name='oid',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
